# Generated by Django 2.0 on 2018-10-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_time',
            new_name='read_num',
        ),
    ]
