# Generated by Django 2.0 on 2018-10-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180224_0212'),
        ('blog', '0008_auto_20181020_2007'),
    ]

    operations = [
    ]
